(in-package #:t-sea-pie)

(in-suite test-all)
(defsuite* test-ngram-frequencies)

(deftest unigrams ()
  (with-input-from-string (stream "hello")
    (multiple-value-bind (freqs ngram-count)
        (gather-letter-ngram-frequencies-from-stream 1 stream)
      (are (= 5 ngram-count)
           (= 4 (hash-table-count freqs))
           (= 1 (gethash "H" freqs 0) (gethash "E" freqs 0) (gethash "O" freqs 0))
           (= 2 (gethash "L" freqs 0))))))

(deftest bigrams ()
  (with-input-from-string (stream "hello elle")
    (multiple-value-bind (freqs ngram-count)
        (gather-letter-ngram-frequencies-from-stream 2 stream)
      (are (= 9 ngram-count)
           (= 7 (hash-table-count freqs))
           (= 1 (gethash "HE" freqs 0))
           (= 2 (gethash "LL" freqs 0))
           (= 1 (gethash "O " freqs 0))))))

(deftest ngrams-normalize-to-word-chars-and-spaces ()
  (with-input-from-string (stream "a a_a+a=a
a*a	a$")
    (multiple-value-bind (freqs ngram-count)
        (gather-letter-ngram-frequencies-from-stream 3 stream)
      (are (= 14 ngram-count)
           (= 2 (hash-table-count freqs))
           (= 7 (gethash "A A" freqs 0))
           (= 7 (gethash " A " freqs 0))))))

(deftest unigram-words ()
  (with-input-from-string (stream "The cat sat on the cat.")
    (multiple-value-bind (freqs ngram-count)
        (gather-word-ngram-frequencies-from-stream 1 stream)
      (are (= 6 ngram-count)
           (= 4 (hash-table-count freqs))
           (= 1
              (gethash '(sat) freqs 0)
              (gethash '(on) freqs 0))
           (= 2
              (gethash '(the) freqs 0)
              (gethash '(cat) freqs 0))))))

(deftest bigram-words ()
  (with-input-from-string (stream "The cat sat on the cat.")
    (multiple-value-bind (freqs ngram-count)
        (gather-word-ngram-frequencies-from-stream 2 stream)
      (are (= 5 ngram-count)
           (= 4 (hash-table-count freqs))
           (= 1 (gethash '(cat sat) freqs 0)
              (gethash '(sat on) freqs 0)
              (gethash '(on the) freqs 0))
           (= 2 (gethash '(the cat) freqs 0))))))
